# Site settings
title: Xiao Li's blog
author: Xiao Li
email: swing1979@gmail.com
description: >
  A software engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://xli.github.io" # the base hostname & protocol for your site
twitter_username: xli
github_username:  xli
excerpt_separator: "<!--more-->"
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap